//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <ctype.h>
#include <signal.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

/* struct _IO_FILE { */
/*     int32_t e0; */
/* }; */

// ------------------- Function Prototypes --------------------

int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_1000(void);
char * function_1030(char * name);
int32_t function_1040(int32_t c);
int32_t function_1050(char * s);
int32_t function_1060(void);
int32_t function_1070(char * s);
int32_t function_1080(char * format, ...);
int32_t function_1090(char * string, int32_t maxlen);
int32_t function_10a0(char * s1, char * s2);
int32_t function_10b0(int32_t pid, int32_t sig);
int64_t * function_10c0(int32_t size);
int32_t function_10d0(int64_t request, ...);
char * function_10e0(char * s, char * delim);
int32_t function_10f0(char ** lineptr, int32_t * n, struct _IO_FILE * stream);
void function_1100(int32_t status);
int16_t ** function_1110(void);
void function_1120(int64_t * d);
int64_t function_1160(void);
int64_t function_1190(void);
int64_t function_11d0(void);
int64_t function_1210(void);
int64_t function_1215(int64_t str, char * a2);
int64_t function_1393(char * format);
int64_t function_13cb(void);
int64_t function_141e(void);
int64_t function_14d0(int64_t a1, int64_t a2, int64_t a3);
int64_t function_1530(void);
int64_t function_1534(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x1210;
int64_t g2 = 0x11d0;
int64_t g3 = 0;
struct _IO_FILE * g4 = NULL;
char g5 = 0;
int32_t g6;

// ------------------------ Functions -------------------------
int64_t hashInput(char * SOYOULYKECATS, unsigned char inputChar, int inputIdx) {
    char * SOYOULYKECATS2 = (char *)(int64_t)SOYOULYKECATS; // bp-72
    /* int32_t inputSize = strnlen((char *)inputStrPtr, 17); // 0x1232 */
    /* int64_t mem = (int64_t)malloc(inputSize); // 0x1242 */
    /* if (inputSize == 0) { */
    /*     // 0x1388 */
    /*     return mem; */
    /* } */

    // Both counters increment by 1
    // Loop breaks when counter pass size of input
    /* int64_t counter_1 = 0; // 0x137b12 */
    /* int32_t counter_2 = 0; */

    int64_t counter_1 = inputIdx; // 0x137b12
    int32_t counter_2 = inputIdx;    
    while (true) {
        int32_t len_SOYOULYKECATS = strlen(SOYOULYKECATS2); // 0x1261
        unsigned char c = *(char *)(counter_1 % (int64_t)len_SOYOULYKECATS + (int64_t)SOYOULYKECATS2); // 0x127b
        int64_t v3 = toupper((int32_t)c) - 65; // 0x1288
        int16_t ** v4 = __ctype_b_loc(); // 0x128e

	// Grab Sequential Character from input
        //char * current_input_element_ptr = (char *)(counter_1 + inputStrPtr); // 0x12a0
	char* current_input_element_ptr = &inputChar;
        int16_t v6 = *(int16_t *)(2 * (int64_t)*current_input_element_ptr + (int64_t)*v4); // 0x12ad
        char v7; // 0x1359
        if ((v6 & 256) == 0) {
            int16_t v8 = *(int16_t *)(2 * (int64_t)*current_input_element_ptr + (int64_t)*__ctype_b_loc()); // 0x1315
            unsigned char v9 = *current_input_element_ptr; // 0x1368
            if ((v8 & 512) != 0) {
                int64_t v10 = v3 - 97 + (int64_t)v9; // 0x133a
                int32_t v11 = v10; // 0x134b
                v7 = v11 + 97 + -26 * ((int32_t)(0x4ec4ec4f * v10 / 0x100000000) / 8 - (v11 >> 31));
            } else {
                v7 = v9;
            }
        } else {
            int64_t v12 = v3 - 65 + (int64_t)*current_input_element_ptr; // 0x12d2
            int32_t v13 = v12; // 0x12e3
            char v14 = v13 + 65 + -26 * ((int32_t)(0x4ec4ec4f * v12 / 0x100000000) / 8 - (v13 >> 31)); // 0x12f1
            v7 = v14;
        }
        // 0x136b
        //*(char *)(counter_1 + mem) = v7;
	return v7;
        /* int32_t v15 = counter_2 + 1; // 0x1377 */
        /* int64_t v16 = v15; */
        /* if ((int64_t)inputSize <= v16) { */
        /*     // break -> 0x1388 */
        /*     break; */
        /* } */
        /* counter_1 = v16; */
        /* counter_2 = v15; */
    }
    // 0x1388
    //return mem;
}


int main(int argn,char** argv) {
  // xzyu{h3v0xev4ln}
  unsigned char* expectedStr = "xzyu{h3v0xev4ln}";
  unsigned char guess[17];
  guess[16] = 0;
  for(int guessIdx = 0; guessIdx < 16; guessIdx++) {
    unsigned char expected = *(expectedStr + guessIdx);
    for(int charIdx = 1; charIdx <= 255; charIdx++) {
      guess[guessIdx] = (unsigned char) charIdx;
      unsigned char hashResult = hashInput("SOYOULYKECATS",(unsigned char) charIdx, guessIdx);
      if(hashResult == expected) {
	break;
      }
    }
  }
  printf("%s\n",(char *) guess);
  return 0;
}
