//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <ctype.h>
#include <signal.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

/* struct _IO_FILE { */
/*     int32_t e0; */
/* }; */

// ------------------- Function Prototypes --------------------

int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_1000(void);
char * function_1030(char * name);
void function_1040(int64_t * ptr);
int32_t function_1050(int32_t c);
int32_t function_1060(char * s);
int32_t function_1070(void);
int32_t function_1080(char * s);
int32_t function_1090(char * format, ...);
int32_t function_10a0(char * s1, char * s2);
int32_t function_10b0(int32_t pid, int32_t sig);
int64_t * function_10c0(int32_t size);
int32_t function_10d0(int64_t request, ...);
char * function_10e0(char * s, char * delim);
int32_t function_10f0(char ** lineptr, int32_t * n, struct _IO_FILE * stream);
void function_1100(int32_t status);
int16_t ** function_1110(void);
void function_1120(int64_t * d);
int64_t function_1160(void);
int64_t function_1190(void);
int64_t function_11d0(void);
int64_t function_1210(void);
int64_t function_1215(char * a1, char * a2);
int64_t function_138f(char * format);
int64_t function_13c7(void);
int64_t function_141a(void);
int64_t function_14e0(int64_t a1, int64_t a2, int64_t a3);
int64_t function_1540(void);
int64_t function_1544(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x1210;
int64_t g2 = 0x11d0;
int64_t g3 = 0;
struct _IO_FILE * g4 = NULL;
char g5 = 0;
int32_t g6;

// ------------------------ Functions -------------------------

int main(int argn,char** argv) {
  function_141a();
  return 0;
}


// Address range: 0x1215 - 0x138f
int64_t function_1215(char * a1, char * a2) {
    int64_t v1 = (int64_t)a1; // 0x121e
    char * str = (char *)v1; // 0x121e
    char * str2 = (char *)(int64_t)a2; // bp-72
    int32_t len = strlen(str); // 0x122d
    int64_t mem = (int64_t)malloc(len); // 0x1235
    if (strlen(str) == 0) {
        // 0x1384
        return mem;
    }
    int64_t v2 = 0; // 0x136c58
    while (true) {
        int32_t len2 = strlen(str2); // 0x1254
        unsigned char c = *(char *)(v2 % (int64_t)len2 + (int64_t)str2); // 0x126e
        int32_t v3 = 65 - toupper((int32_t)c);
        int16_t ** v4 = __ctype_b_loc(); // 0x1281
        char * v5 = (char *)(v2 + v1); // 0x1293
        int16_t v6 = *(int16_t *)(2 * (int64_t)*v5 + (int64_t)*v4); // 0x12a0
        char v7; // 0x1366
        if ((v6 & 256) == 0) {
            int16_t v8 = *(int16_t *)(2 * (int64_t)*v5 + (int64_t)*__ctype_b_loc()); // 0x1307
            unsigned char v9 = *v5; // 0x1359
            if ((v8 & 512) != 0) {
                int32_t v10 = v3 - 71 + (int32_t)v9; // 0x1329
                v7 = v10 + 97 + -26 * (v10 / 26 - (v10 >> 31));
            } else {
                v7 = v9;
            }
        } else {
            int32_t v11 = v3 - 39 + (int32_t)*v5; // 0x12c2
            v7 = v11 + 65 + -26 * (v11 / 26 - (v11 >> 31));
        }
        // 0x135c
        *(char *)(v2 + mem) = v7;
        int64_t v12 = v2 + 1 & 0xffffffff;
        if (v12 >= (int64_t)strlen(str)) {
            // break -> 0x136c
            break;
        }
        v2 = v12;
    }
    // 0x1384
    return mem;
}

// Address range: 0x141a - 0x14d7
int64_t function_141a(void) {
  int64_t str = function_1215("xzyu{hfkxcbhmloaoftay}", "SOYOULYKECATS");
  printf("%s\n",(char *)str);  
  return 0;
}
